name: "aws_dbt_snowflake_project"
version: "1.0.0"

profile: "aws_dbt_snowflake_project"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  aws_dbt_snowflake_project: # name of the project folder
    demo: # name of the model (/models/demo/demo.sql) - refers to the folder name (2)
      +materialized: table # type of file created in snowflake (table, view, incremental, ephemeral)
